### ISSUE TITLE
Put js-ipfs in a Service Worker

### ISSUE THREAD

**Issue by daviddias** [peer-base/peer-pad#135]
Here is an idea. In order to solve the "multi tab" issue, the js-ipfs node for PeerPad can be spin up on a Service Worker -- https://github.com/ipfs/ipfs-service-worker -- and then we can use the work that @alanshaw has been doing on postmsg-rpc -- https://youtu.be/qTOUMWujoEg -- to talk with the node.

**Comment by diasdavid** [comment]
This could also improv PeerPad perf since js-ipfs would run on a separate thread.

Can also be interesting for orbit.chat //cc @haadcode

**Comment by alanshaw** [comment]
I'm pretty sure [`ipfs-postmsg-proxy`](https://github.com/tableflip/ipfs-postmsg-proxy) could be adapted or forked for this.

**Comment by pgte** [comment]
@diasdavid That's a great idea. I'll be toying around with this in the next days.

**Comment by haadcode** [comment]
Agreed this is a great idea 👍 Not just for orbit.chat but in general I believe this pattern will help a lot of (browser) app devs. The way we currently have to put everything into one thread is quite heavy for apps..
