### ISSUE TITLE
How can I tell if my Pad has been pinned?

### ISSUE THREAD

**Issue by daviddias** [peer-base/peer-pad#251]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1211152/49372870-00c28000-f6f4-11e8-93c7-953d3530527f.png">

As far as I can see, the UI doesn't tell me the state of persistence yet.

**Comment by pgte** [comment]
See dev.peerpad.net

**Comment by daviddias** [comment]
Niiiiiiceeeeeee!! <3 

<img width="169" alt="image" src="https://user-images.githubusercontent.com/1211152/49373232-28feae80-f6f5-11e8-971c-c7d4c5505577.png">

**Comment by daviddias** [comment]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/1211152/49373239-2f8d2600-f6f5-11e8-8a61-260885c23112.png">

oh :(

**Comment by pgte** [comment]
It's the peer discovery time that is large (which is [being worked on here](https://github.com/ipfs-shipyard/peer-star-app/pull/176)).

But once the pinner peer is discovered, it should get saved.

It happened ok for me:

![peerpad](https://user-images.githubusercontent.com/47910/49373401-edb0af80-f6f5-11e8-8588-932701724082.png)

@daviddias has it worked out for you?

**Comment by pgte** [comment]
Related: https://github.com/ipfs-shipyard/peer-star-app/issues/189
