### ISSUE TITLE
Landscape of Open Collaborative Text Editors

### ISSUE THREAD

**Issue by daviddias** [peer-base/peer-pad#317]
Leaving this article here https://juretriglav.si/open-source-collaborative-text-editors/, it provides a good update on the state of text editors everywhere, might spark some ideas for PeerPad :)

**Comment by daviddias** [comment]
Also, the illustration cracked me open 

![image](https://user-images.githubusercontent.com/1211152/57273358-c0e33880-7097-11e9-87bb-86c4ae12480f.png)

**Comment by jimpick** [comment]
Related Hacker News thread: https://news.ycombinator.com/item?id=19845776

I'd already left some breadcrumbs leading over to PeerPad. :-)
